name: CI/CD DevOps Final

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Obtener el código del repo
      - name: Checkout
        uses: actions/checkout@v3

      # 2) Instalar .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      # 3) Restaurar dependencias
      - name: Restore dependencies
        run: dotnet restore

      # 4) Ejecución de pruebas unitarias
      - name: Run Unit Tests
        run: dotnet test --no-build --verbosity normal

      # 5) Login a Docker Hub
      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 6) Build + Push imagen Docker
      - name: Build & Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USER }}/hola-mundo:latest

      # 7) Deploy a Render
      - name: Deploy to Render
        uses: johnbeynon/render-deploy-action@v1
        with:
          service-id: ${{ secrets.RENDER_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}
